
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  api_version: 2
  ssl: false
  host: influxdb
  port: 8086
  token: admintoken123
  organization: it
  bucket: cassiopeiainflux
  include:
    entities:
      - sensor.temperature_1
